spring.application.name=spring-data
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-time=86400000

mail.host=smtp.gmail.com
mail.port=587
mail.username=demo@gmail.com
mail.password=password
mail.auth=true
mail.starttls=true

pdf.output.path=C:/Users/czikac/Desktop/generated_document.pdf
pdf.existing.path=C:/Users/czikac/Desktop/existing_document.pdf
pdf.modified.path=C:/Users/czikac/Desktop/modified_document.pdf
pdf.sample.image=C:/Users/czikac/Desktop/image.jpg