spring.application.name=spring-app
server.port=8081
spring.profiles.active=dev

security.controller.timeout=300000

app.mail.host=example.com
app.mail.port=587
app.mail.username=your_username
app.mail.password=your_password